version: "3"
services:
  core:
    build: ./
    volumes:
      - ./:/work
    ulimits:
      memlock: -1
    environment:
      - "CUDA_VISIBLE_DEVICES=all"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
