version: "3"
services:
  reazonspeech:
    build: ./
    working_dir: /work
    volumes:
      - ./:/work
      - /root/nltk_data
      - /tmp
    ulimits:
      memlock: -1
    environment:
      - "CUDA_VISIBLE_DEVICES=0"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
